AplicacaoTeste/Controllers/AlunoController.cs
using AplicacaoTeste.Dados.Entidades;
using AplicacaoTeste.Dados.Servico;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AplicacaoTeste.Controllers
{
    public class AlunoController : Controller
    {
        private readonly AlunoServico _servico;
        public AlunoController()
        {
            _servico = new AlunoServico();
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            try
            {
                var todosAlunos = _servico.ObtemAlunos();
                return PartialView("_List", todosAlunos);
            }
            catch (Exception e)
            {
                TempData["Error"] = e.Message;
                return PartialView("_List", new List<Aluno>());
            }
         
        }

        public ActionResult Cadastrar()
        {
           return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Aluno model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = _servico.Insert(model);
                    if (result > 0)
                    {
                        TempData["Success"] = "Solicitação processada com sucesso!";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Error"] = "Ocorreu um erro ao tentar processar a sua solicitação!";
                    }
                   
                }

                return View("Cadastrar", model);

            }
            catch (Exception e)
            {
                TempData["Error"] = "Ocorreu um erro ao tentar processar a sua solicitação!";
                return RedirectToAction("Index");
            }
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AplicacaoTeste/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AplicacaoTeste.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AplicacaoTeste/Views/Aluno/Cadastrar.cshtml
@model AplicacaoTeste.Dados.Entidades.Aluno
@{
    //Layout = null;
}


@using (Html.BeginForm())
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Cadastro de alunos Phidelis</h3>
        </div>
        <div class="panel-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.NomeCompleto, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.NomeCompleto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NomeCompleto, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.DataDeNascimento, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.DataDeNascimento, new { htmlAttributes = new { @class = "form-control", @type="date" } })
                        @Html.ValidationMessageFor(model => model.DataDeNascimento, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-sm btn-success radius-50 vine"><i class="fa fa-send">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</i> SALVAR </button>
        </div>
    </div>


}

AplicacaoTeste/Views/Aluno/Contact.cshtml
@model AplicacaoTeste.Dados.Entidades.Aluno


<form>
    <div class="form-group">
        <label for="exampleFormControlInput1">Email address</label>
        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
    </div>
</form>

AplicacaoTeste/Views/Aluno/Index.cshtml
@{
    var mensagemErro = TempData["Error"] != null ? TempData["Error"].ToString() : string.Empty;
    var mensagemSucesso = TempData["Success"] != null ? TempData["Success"].ToString() : string.Empty;
}

<blockquote style="margin-top:10px!important">
    <h3 class="page-title text-uppercase"><i class="glyphicon glyphicon-user"> &nbsp; </i>Alunos da escola</h3>
</blockquote>

<div class="row">
    <div class="col-md-2">
        <a href="@Url.Action("Cadastrar")" class="btn btn-primary">
            Cadastrar aluno
        </a>
    </div>
</div>

<div class="row">

    <div class="col-md-12">
        <br />
        @if (!string.IsNullOrEmpty(mensagemErro))
        {
            <div class="alert alert-danger">
                <p>
                    <i class="glyphicon glyphicon-alert">&nbsp;</i> Ops! Ocorreu um erro ao tentar processar a sua solicitação:

                </p>
            </div>
        }

        @if (!string.IsNullOrEmpty(mensagemSucesso))
        {
            <div class="alert alert-success">
                <p>
                    @mensagemSucesso
                </p>
            </div>
        }
    </div>

    <br />
    <div class="col-md-12">
        <div class="pv-30 ph-20 white-bg feature-box bordered">
            @{
                Html.RenderAction("List");
            }
        </div>
    </div>
</div>

AplicacaoTeste/Views/Aluno/_List.cshtml
@model List<AplicacaoTeste.Dados.Entidades.Aluno>

<div class="row">

    <div class="col-md-12">
        <div class="pv-30 ph-20 white-bg feature-box bordered">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Matricula
                        </th>
                        <th>
                            Nome
                        </th>
                        <th>
                            Data de nascimento
                        </th>
                        <th>
                            CPF
                        </th>
                        <th>
                            Ações
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var aluno in Model)
                    {
                        <tr>
                            <td>
                                @aluno.IdAluno
                            </td>
                            <td>
                                @aluno.Matricula
                            </td>
                            <td>
                                @aluno.NomeCompleto
                            </td>
                            @*Colocar no formato dd/MM/yyyy*@
                            <td>
                                @aluno.DataDeNascimento
                            </td>
                            <td>
                                @aluno.Cpf
                            </td>
                            <td>
                                <button class="btn btn-default">Alterar</button>
                                <button class="btn btn-danger">Remover</button>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

AplicacaoTeste/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AplicacaoTeste/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AplicacaoTeste/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Phidelis Tecnologia</h1>
    <p class="lead">Bem vindo ao sistema de avaliação Phidelis.</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Vamos começar?</h2>
        <p>
            É permitido utilizar os recursos de internet para realizar pesquisas relacionadas a essa avaliação.
        </p>
        <p>
            Caso ocorra algum problema de hardware, falta de conexão com a internet, ou qualquer outra situação que impeça o prosseguimento do teste, informe imediatamente à equipe de aplicação de prova para que as
            medidas cabíveis possam ser tomadas.
        </p>
        <blockquote>
            <p>
                O tempo de prova é de <strong>2h30</strong>.
            </p>
        </blockquote>
    </div>
    <div class="col-md-4">
        <h2>Leia o enunciado</h2>
        <p>Clique aqui para visualizar os desafios dessa avaliação.</p>
        <p><a class="btn btn-default" href="~/Avaliação Phidelis.docx">Visualizar enunciado</a></p>
    </div>
</div>

AplicacaoTeste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Avaliação Phidelis</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Avaliação Phidelis", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Alunos", "Index", "Aluno")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:40px !important">

        <div class="row">
            <div class="col-md-12 col-lg-12">
                @RenderBody()
            </div>
        </div>
     
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Phidelis Tecnologia</p>
        </footer>
    </div>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id='myModalContent'></div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="myModalLg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div id='myModalContentLg'></div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>